### PR TITLE
Remove old code overwriting template.js css. Allow custom template se…

### PR DESCRIPTION
**Pull request by sleepycandle**
…ttings to be passed when template is being created.

### CODE REVIEW

**Comment by ewnd9** [comment]
Please revert the changes in `src/template.js` (`background-color`) and I will merge it.

This property is missing in the ruby port I originated from:

https://github.com/albertzak/anki2/blob/d19a74285f1caa22c3e28643e80713ce35ddf482/lib/anki2.rb#L187-L190

But presented in both `anki` and `AnkiDroid` sources:

https://github.com/dae/anki/blob/bd414595de971ac29b54d521d734140eee7d80ee/anki/models.py#L36-L41

https://github.com/ankidroid/Anki-Android/blob/dbbf3ea6549e82dee9e3c0df39bb5c3f74d3e189/AnkiDroid/src/main/java/com/ichi2/libanki/Models.java#L69-L74

**Comment by ewnd9** [comment]
Also, there's no need to create a new pull request as you did with https://github.com/ewnd9/anki-apkg-export/pull/29

Just do the following after adding back the css property:

```sh
$ git add src/template.js
$ git commit --amend
$ git push origin master --force
```

It will rewrite the original commit and update this pull request.

**Comment by sleepycandle** [comment]
Hello I've reverted changes to template.js thanks for the help. Sorry for the extra pull request.

**Comment by ewnd9** [comment]
Thanks, published as `v4.0.1` after updating the sample in `test/fixtures/output.apkg` to fix tests :+1:

**Pull request merged**
